apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: file-browser
  name: file-browser
  namespace: filebrowser
spec:
  replicas: 1
  selector:
    deploymentconfig: file-browser
  template:
    metadata:
      labels:
        deploymentconfig: file-browser
    spec:
      containers:
      - image: quay.io/smitaraut/filebrowser:latest
        name: file-browser-container
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /srv
          name: mypvc
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: fb-pvc
            readOnly: false
