apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: filebrowser
  name: filebrowser
  namespace: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - image: filebrowser/filebrowser:v2
        name: filebrowser
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /srv
          name: filebrowser
      volumes:
        - name: filebrowser
          persistentVolumeClaim:
            claimName: afm-pvc
            readOnly: false
