apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: filebrowser-isf
  name: filebrowser-isf
  namespace: file-browser
spec:
  replicas: 1
  selector:
    deploymentconfig: filebrowser-isf
  template:
    metadata:
      labels:
        deploymentconfig: filebrowser-isf
    spec:
      containers:
      - image: filebrowser/filebrowser:latest
        name: filebrowser-isf
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /srv
          name: filebrowser-isf
      volumes:
        - name: filebrowser-isf
          persistentVolumeClaim:
            claimName: afm-pvc
            readOnly: true