apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  selector:
    matchLabels:
      app: filebrowser
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: filebrowser
    weight: 100
