apiVersion: v1
kind: Service
metadata:
  labels:
    app: filebrowser-isf
  name: filebrowser-isf
  namespace: file-browser
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    deploymentconfig: filebrowser-isf
