apiVersion: v1
kind: Service
metadata:
  name: file-browser
  labels:
    app: file-browser
  namespace: filebrowser
spec:
  ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    deploymentconfig: file-browser
