---
    apiVersion: app.k8s.io/v1beta1
    kind: Application
    metadata:
      name: filebrowser
      namespace: filebrowser
    spec:
      selector:
        matchLabels:
          app: filebrowser