apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: file-browser
  labels:
    app: file-browser
  namespace: filebrowser
spec:
  port:
    targetPort: 80-tcp
  to:
    kind: Service
    name: file-browser
