apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: filebrowser
  name: filebrowser
  namespace: filebrowser
spec:
  replicas: 1
  selector:
    deploymentconfig: filebrowser
  template:
    metadata:
      labels:
        deploymentconfig: filebrowser
    spec:
      containers:
      - image: quay.io/smitaraut/filebrowser:latest
        name: file-browser-container
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /srv
          name: mypvc
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: fb-app
            readOnly: false
