apiVersion: v1
kind: Service
metadata:
  labels:
    app: filebrowser
  name: filebrowser
  namespace: filebrowser
spec:
  ports:
  - name: 81-tcp
    port: 81
    protocol: TCP
    targetPort: 81
  selector:
    deploymentconfig: filebrowser
